### ISSUE TITLE
Mistakes

### ISSUE THREAD

**Issue by faded53222** [goelp14/RockPaperScissors#2]
edited

**Comment by goelp14** [comment]
Hello @faded53222 thank you for responding! The AI part of this code is with the Intermediate mode. If you have found a mistake with my random game mode please be more specific so I can address the problem or you should go ahead and make a pull request addressing the problem. This is a pure python code with no intention of being part of a website. However, if you would want to integrate it with a website I would encourage you to give it a go (with the right accreditation of course)!

**Comment by faded53222** [comment]
I comment at the wrong place.....Sorry.
I was supposed to comment at another object which is html.
But I wrongly click in yours.Sorry.
Give you a star by way of apology. 
And I will close the issue once I got your response.

**Comment by goelp14** [comment]
@faded53222 Thank you for telling me!
